#! /bin/sh

########################################################
#########################   Bspwm    ###################
########################################################

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

bspc monitor -d 1 2 3 4  

bspc config border_width         2
bspc config window_gap           12
bspc config bottom_padding       0
bspc config left_padding         0 
bspc config right_padding        0
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors   true
bspc config remove_disabled_monitors     true
bspc config history_aware_focus         true


bspc rule -a firefox 
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pamac-manager state=floating
bspc rule -a Pavucontrol state= floating
bspc rule -a Galculator state=floating 

# Border
bspc config focused_border_color        "#44475a"
bspc config normal_border_color         "#44475a"
bspc config active_border_color         "#44475a"
bspc config presel_feedback_color        "#44475a"


##########################################################
########################   Autostart   ###################
##########################################################

# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh &

# wallpaper 
nitrogen --restore &

# Bar
#~/.config/polybar/launch.sh &
# $HOME/.config/polybar/launch.sh --cuts &
#pkill yabar; ~/.config/yabar/yabar-setup.sh; yabar -c /tmp/yabar.conf
polybar example &
~/panaz/nyowan &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &  

# Picom
#picom -CGb &
#picom &

# Network Applet
nm-applet --indicator &

# Cursor
#xsetroot -cursor_name left_ptr &

# Low battery notifier
#~/.config/bspwm/scripts/low_bat_notifier.sh &


